"""Markdown onboarding guide generator.

Produces a comprehensive Markdown guide from scan results,
architecture maps, git analysis, and AI summaries.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from ..scanner import ScanResult
from ..analyzer import ArchitectureMap
from ..git_analyzer import GitAnalysis
from ..engine import AISummary


def generate_guide_markdown(
    scan: ScanResult,
    arch: ArchitectureMap,
    git: GitAnalysis | None,
    ai: AISummary | None,
) -> str:
    """Generate the full onboarding guide as Markdown."""
    sections: list[str] = []

    # Header
    repo_name = scan.root.name
    sections.append(f"# Onboarding Guide: {repo_name}\n")
    sections.append(f"*Generated by [Onboard](https://github.com/Jaxz714/onboard) on {datetime.now().strftime('%Y-%m-%d %H:%M')}*\n")
    sections.append("---\n")

    # Table of contents
    toc = [
        "## Table of Contents\n",
        "1. [Overview](#overview)",
        "2. [Quick Start](#quick-start)",
        "3. [Architecture](#architecture)",
        "4. [Project Structure](#project-structure)",
        "5. [Dependencies](#dependencies)",
        "6. [Modules](#modules)",
        "7. [Entry Points](#entry-points)",
        "8. [Testing](#testing)",
        "9. [Git Activity](#git-activity)",
        "10. [Where to Start](#where-to-start)",
    ]
    sections.append("\n".join(toc) + "\n")
    sections.append("---\n")

    # 1. Overview
    sections.append("## Overview\n")
    if ai and ai.overview:
        sections.append(ai.overview + "\n")
    else:
        sections.append(_generate_overview_text(scan, arch) + "\n")

    # 2. Quick Start
    sections.append("## Quick Start\n")
    sections.append(_generate_quick_start(scan, arch) + "\n")

    # 3. Architecture
    sections.append("## Architecture\n")
    if ai and ai.architecture_notes:
        sections.append(ai.architecture_notes + "\n")
    sections.append(_generate_architecture_section(arch) + "\n")

    # 4. Project Structure
    sections.append("## Project Structure\n")
    sections.append(_generate_structure_tree(scan) + "\n")

    # 5. Dependencies
    sections.append("## Dependencies\n")
    sections.append(_generate_dependencies_section(scan) + "\n")

    # 6. Modules
    sections.append("## Modules\n")
    sections.append(_generate_modules_section(arch, ai) + "\n")

    # 7. Entry Points
    sections.append("## Entry Points\n")
    sections.append(_generate_entry_points_section(scan) + "\n")

    # 8. Testing
    sections.append("## Testing\n")
    sections.append(_generate_testing_section(scan) + "\n")

    # 9. Git Activity
    if git:
        sections.append("## Git Activity\n")
        sections.append(_generate_git_section(git) + "\n")

    # 10. Where to Start
    sections.append("## Where to Start\n")
    if ai and ai.getting_started:
        sections.append(ai.getting_started + "\n")
    else:
        sections.append(_generate_where_to_start(scan, arch) + "\n")

    return "\n".join(sections)


# ---------------------------------------------------------------------------
# Section generators
# ---------------------------------------------------------------------------

def _generate_overview_text(scan: ScanResult, arch: ArchitectureMap) -> str:
    lines: list[str] = []
    langs = sorted(scan.by_language.items(), key=lambda x: -x[1])
    lang_str = ", ".join(f"**{l}** ({c} files)" for l, c in langs[:5]) if langs else "various languages"
    lines.append(f"This repository contains **{scan.total_files}** files "
                 f"({scan.total_size / 1024:.0f} KB) written in {lang_str}.")
    if scan.detected_patterns:
        lines.append(f"\n**Architecture patterns detected:** {', '.join(scan.detected_patterns)}.")
    return "\n".join(lines)


def _generate_quick_start(scan: ScanResult, arch: ArchitectureMap) -> str:
    lines: list[str] = []
    lines.append("### Prerequisites\n")

    # Guess from dependency files
    for dep in scan.dependencies:
        if dep.manager == "npm":
            lines.append("- Node.js and npm (or yarn/pnpm)")
        elif "pip" in dep.manager:
            lines.append("- Python 3.10+")
        elif dep.manager == "go":
            lines.append("- Go 1.18+")
        elif dep.manager == "cargo":
            lines.append("- Rust and Cargo")
        elif dep.manager == "maven":
            lines.append("- Java and Maven")

    if not scan.dependencies:
        lines.append("- See project configuration files for prerequisites")

    lines.append("\n### Installation\n")

    for dep in scan.dependencies:
        if dep.manager == "npm":
            lines.append("```bash\nnpm install\n```")
        elif "pip" in dep.manager:
            if dep.file.endswith("pyproject.toml"):
                lines.append("```bash\npip install -e .\n```")
            else:
                lines.append(f"```bash\npip install -r {Path(dep.file).name}\n```")
        elif dep.manager == "go":
            lines.append("```bash\ngo mod download\n```")
        elif dep.manager == "cargo":
            lines.append("```bash\ncargo build\n```")
        elif dep.manager == "maven":
            lines.append("```bash\nmvn install\n```")

    if not scan.dependencies:
        lines.append("See the project's README for installation instructions.")

    return "\n".join(lines)


def _generate_architecture_section(arch: ArchitectureMap) -> str:
    lines: list[str] = []

    lines.append("### Language Distribution\n")
    lines.append("| Language | Files |")
    lines.append("|----------|-------|")
    for lang, count in sorted(arch.language_breakdown.items(), key=lambda x: -x[1]):
        lines.append(f"| {lang} | {count} |")
    lines.append("")

    lines.append("### File Categories\n")
    lines.append("| Category | Count |")
    lines.append("|----------|-------|")
    for cat, count in sorted(arch.category_breakdown.items(), key=lambda x: -x[1]):
        lines.append(f"| {cat} | {count} |")
    lines.append("")

    if arch.patterns:
        lines.append("### Detected Patterns\n")
        for p in arch.patterns:
            lines.append(f"- {p}")
        lines.append("")

    return "\n".join(lines)


def _generate_structure_tree(scan: ScanResult) -> str:
    """Generate a simplified directory tree."""
    lines: list[str] = ["```\n"]

    # Build tree from directories
    top_dirs = sorted(set(
        d.split("/")[0] for d in scan.directories
        if d and "/" not in d
    ))

    lines.append(f"{scan.root.name}/")
    for d in top_dirs:
        # Count files in this directory (direct children)
        direct_files = [f for f in scan.files if f.relative.startswith(d + "/") and "/" not in f.relative[len(d) + 1:]]
        file_count = len(direct_files)
        lines.append(f"  {d}/  ({file_count} files)")

        # Show subdirectories
        sub_dirs = sorted(set(
            f.relative.split("/")[1]
            for f in scan.files
            if f.relative.startswith(d + "/") and f.relative.count("/") >= 2
        ))
        for sd in sub_dirs[:5]:
            lines.append(f"    {sd}/")
        if len(sub_dirs) > 5:
            lines.append(f"    ... and {len(sub_dirs) - 5} more directories")

    # Root-level files
    root_files = [f for f in scan.files if "/" not in f.relative]
    if root_files:
        lines.append(f"  ({len(root_files)} files at root)")

    lines.append("```")
    return "\n".join(lines)


def _generate_dependencies_section(scan: ScanResult) -> str:
    if not scan.dependencies:
        return "No dependency files found.\n"

    lines: list[str] = []
    for dep in scan.dependencies:
        lines.append(f"### {dep.manager} (`{dep.file}`)\n")

        if dep.dependencies:
            lines.append("**Dependencies:**\n")
            lines.append("| Package | Version |")
            lines.append("|---------|---------|")
            for name, version in sorted(dep.dependencies.items()):
                lines.append(f"| {name} | {version} |")
            lines.append("")

        if dep.dev_dependencies:
            lines.append("<details><summary>Dev Dependencies</summary>\n")
            lines.append("| Package | Version |")
            lines.append("|---------|---------|")
            for name, version in sorted(dep.dev_dependencies.items()):
                lines.append(f"| {name} | {version} |")
            lines.append("\n</details>\n")

    return "\n".join(lines)


def _generate_modules_section(arch: ArchitectureMap, ai: AISummary | None) -> str:
    lines: list[str] = []

    for mod in sorted(arch.modules, key=lambda m: -m.file_count):
        markers = []
        if mod.is_entry_point:
            markers.append("ENTRY POINT")
        if mod.is_test:
            markers.append("TEST")
        marker_str = f" [{', '.join(markers)}]" if markers else ""

        lines.append(f"### `{mod.name}`{marker_str}\n")
        lines.append(f"- **Files:** {mod.file_count}")
        if mod.languages:
            lang_str = ", ".join(f"{l} ({c})" for l, c in sorted(mod.languages.items(), key=lambda x: -x[1]))
            lines.append(f"- **Languages:** {lang_str}")
        if mod.purpose:
            lines.append(f"- **Purpose:** {mod.purpose}")
        if mod.key_files:
            lines.append(f"- **Key files:** {', '.join(f'`{f}`' for f in mod.key_files[:5])}")

        # AI module summary
        if ai and ai.module_summaries and mod.name in ai.module_summaries:
            lines.append(f"\n{ai.module_summaries[mod.name]}\n")
        else:
            lines.append("")

    return "\n".join(lines)


def _generate_entry_points_section(scan: ScanResult) -> str:
    if not scan.entry_points:
        return "No obvious entry points detected. Check the project's README for how to run it.\n"

    lines: list[str] = ["The following entry points were detected:\n"]
    for ep in scan.entry_points:
        lines.append(f"- `{ep}`")
    lines.append("")
    return "\n".join(lines)


def _generate_testing_section(scan: ScanResult) -> str:
    test_files = [f for f in scan.files if f.category == "test"]
    lines: list[str] = []

    if not test_files:
        return "No test files detected.\n"

    lines.append(f"**{len(test_files)} test files** found across {len(scan.test_dirs)} directories:\n")
    for td in scan.test_dirs:
        lines.append(f"- `{td}/`")
    lines.append("")

    # Sample test files
    lines.append("Sample test files:\n")
    for tf in test_files[:10]:
        lines.append(f"- `{tf.relative}`")
    if len(test_files) > 10:
        lines.append(f"- ... and {len(test_files) - 10} more")
    lines.append("")

    return "\n".join(lines)


def _generate_git_section(git: GitAnalysis) -> str:
    lines: list[str] = []
    lines.append(f"- **Branch:** `{git.branch}`")
    lines.append(f"- **Total commits:** {git.total_commits}")
    if git.repo_age:
        lines.append(f"- **First commit:** {git.repo_age}")
    lines.append("")

    if git.recent_commits:
        lines.append("### Recent Commits\n")
        lines.append("| Hash | Author | Date | Message |")
        lines.append("|------|--------|------|---------|")
        for c in git.recent_commits[:10]:
            msg = c["message"][:60].replace("|", "\\|")
            lines.append(f"| `{c['hash']}` | {c['author']} | {c['date'][:10]} | {msg} |")
        lines.append("")

    if git.top_changed_files:
        lines.append("### Most Frequently Changed Files\n")
        lines.append("| File | Changes | Contributors |")
        lines.append("|------|---------|--------------|")
        for fs in git.top_changed_files:
            contribs = ", ".join(fs.contributors[:2]) or "-"
            lines.append(f"| `{fs.path}` | {fs.change_count} | {contribs} |")
        lines.append("")

    if git.hotspots:
        lines.append("### Hotspots (high-churn files)\n")
        lines.append("These files are changed frequently and may be complex or critical:\n")
        for h in git.hotspots[:10]:
            lines.append(f"- `{h}`")
        lines.append("")

    return "\n".join(lines)


def _generate_where_to_start(scan: ScanResult, arch: ArchitectureMap) -> str:
    lines: list[str] = []

    if scan.entry_points:
        lines.append("### Entry Points\n")
        lines.append("Start by reading these files to understand how the application starts:\n")
        for ep in scan.entry_points[:5]:
            lines.append(f"- `{ep}`")
        lines.append("")

    lines.append("### Configuration Files\n")
    lines.append("Understanding these will help you know how the project is set up:\n")
    for cf in scan.config_files[:10]:
        lines.append(f"- `{cf}`")
    lines.append("")

    lines.append("### Suggested Reading Order\n")
    reading_order = []

    # README first
    readme = [f for f in scan.files if f.path.name.lower().startswith("readme")]
    if readme:
        reading_order.append(readme[0].relative)

    # Entry points
    for ep in scan.entry_points[:3]:
        if ep not in reading_order:
            reading_order.append(ep)

    # Key configs
    for cf in scan.config_files[:3]:
        if cf not in reading_order:
            reading_order.append(cf)

    for i, f in enumerate(reading_order, 1):
        lines.append(f"{i}. `{f}`")
    lines.append("")

    return "\n".join(lines)
